name: âŒ Replicate Checkout Error

on:
  push:
    branches:
      - "*"
    paths:
      - "docs/*.md"
      - "casanovo/casanovo.py"
      - ".github/workflows/replicate-error.yml"
  pull_request:
    paths:
      - "docs/*.md"
      - "casanovo/casanovo.py"
  workflow_dispatch:

jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: âŒ Check out the repo with ref (this will break in forks)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: ğŸ“¦ Install your package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: ğŸ¨ Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          timeout: 10
          commit_changes: "true"
          clean_img_paths: docs/images/*.svg